plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.4

inherit_from:
  - ./rubocop/rubocop.yml
  - ./rubocop/rubocop-rspec.yml
  - ./rubocop/rubocop-rails.yml
  - ./rubocop/rubocop-rspec_rails.yml
